# Generated by Django 2.1.5 on 2019-02-16 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Loại Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Sản phẩm ban đầu'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name_plural': 'Sản phẩm change'},
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='trạng thái'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Loại sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='giá tiền'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/', verbose_name='Ảnh sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='Tồn kho'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Giá tiền'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='sản phẩm'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='Giá sale'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Tiêu đề'),
        ),
    ]
