# Generated by Django 2.1.5 on 2019-02-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190217_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Sản phẩm'},
        ),
    ]
