# Generated by Django 2.1.5 on 2019-02-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20190216_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session',
        ),
    ]
